"Aruba" : "ABW"
"Afghanistan" : "AFG"
"Angola" : "AGO"
"Anguilla" : "AIA"
"Aland Islands" : "ALA"
"Albania" : "ALB"
"Andorra" : "AND"
"United Arab Emirates" : "ARE"
"Argentina" : "ARG"
"Armenia" : "ARM"
"American Samoa" : "ASM"
"Antarctica" : "ATA"
"Antigua and Barbuda" : "ATG"
"Australia" : "AUS"
"Austria" : "AUT"
"Azerbaijan" : "AZE"
"Burundi" : "BDI"
"Belgium" : "BEL"
"Benin" : "BEN"
"Burkina Faso" : "BFA"
"Bangladesh" : "BGD"
"Bulgaria" : "BGR"
"Bahrain" : "BHR"
"Bahamas" : "BHS"
"Bosnia and Herzegovina" : "BIH"
"Saint Barthelemy" : "BLM"
"Belarus" : "BLR"
"Belize" : "BLZ"
"Bermuda" : "BMU"
"Bolivia" : "BOL"
"Brazil" : "BRA"
"Barbados" : "BRB"
"Brunei Darussalam" : "BRN"
"Bhutan" : "BTN"
"Botswana" : "BWA"
"Central African Republic" : "CAF"
"Canada" : "CAN"
"Switzerland" : "CHE"
"Chile" : "CHL"
"China" : "CHN"
"Ivory Coast" : "CIV"
"Cameroon" : "CMR"
"Congo, the Democratic Republic of the" : "COD"
"Congo" : "COG"
"Cook Islands" : "COK"
"Colombia" : "COL"
"Comoros" : "COM"
"Cape Verde" : "CPV"
"Costa Rica" : "CRI"
"Cuba" : "CUB"
"Curacao" : "CUW"
"Cayman Islands" : "CYM"
"Cyprus" : "CYP"
"Czech Republic" : "CZE"
"Germany" : "DEU"
"Djibouti" : "DJI"
"Dominica" : "DMA"
"Denmark" : "DNK"
"Dominican Republic" : "DOM"
"Algeria" : "DZA"
"Ecuador" : "ECU"
"Egypt" : "EGY"
"Eritrea" : "ERI"
"Western Sahara" : "ESH"
"Spain" : "ESP"
"Estonia" : "EST"
"Ethiopia" : "ETH"
"Finland" : "FIN"
"Fiji" : "FJI"
"Falkland Islands (Malvinas)" : "FLK"
"France" : "FRA"
"Micronesia, Federated States of" : "FSM"
"Gabon" : "GAB"
"United Kingdom" : "GBR"
"Georgia" : "GEO"
"Guernsey" : "GGY"
"Ghana" : "GHA"
"Gibraltar" : "GIB"
"Guinea" : "GIN"
"Guadeloupe" : "GLP"
"Gambia" : "GMB"
"Guinea-Bissau" : "GNB"
"Equatorial Guinea" : "GNQ"
"Greece" : "GRC"
"Grenada" : "GRD"
"Greenland" : "GRL"
"Guatemala" : "GTM"
"French Guiana" : "GUF"
"Guam" : "GUM"
"Guyana" : "GUY"
"Hong Kong" : "HKG"
"Honduras" : "HND"
"Croatia" : "HRV"
"Haiti" : "HTI"
"Hungary" : "HUN"
"Indonesia" : "IDN"
"India" : "IND"
"Ireland" : "IRL"
"Iran" : "IRN"
"Iraq" : "IRQ"
"Iceland" : "ISL"
"Israel" : "ISR"
"Italy" : "ITA"
"Jamaica" : "JAM"
"Jordan" : "JOR"
"Japan" : "JPN"
"Kazakhstan" : "KAZ"
"Kenya" : "KEN"
"Kyrgyzstan" : "KGZ"
"Cambodia" : "KHM"
"Kiribati" : "KIR"
"South Korea, Republic of" : "KOR"
"Kuwait" : "KWT"
"Lao People's Democratic Republic" : "LAO"
"Lebanon" : "LBN"
"Liberia" : "LBR"
"Libya" : "LBY"
"Liechtenstein" : "LIE"
"Sri Lanka" : "LKA"
"Lesotho" : "LSO"
"Lithuania" : "LTU"
"Luxembourg" : "LUX"
"Latvia" : "LVA"
"Macao" : "MAC"
"Morocco" : "MAR"
"Monaco" : "MCO"
"Moldova, Republic of" : "MDA"
"Madagascar" : "MDG"
"Maldives" : "MDV"
"Mexico" : "MEX"
"Marshall Islands" : "MHL"
"Macedonia, the former Yugoslav Republic of" : "MKD"
"Mali" : "MLI"
"Malta" : "MLT"
"Myanmar" : "MMR"
"Montenegro" : "MNE"
"Mongolia" : "MNG"
"Mozambique" : "MOZ"
"Mauritania" : "MRT"
"Montserrat" : "MSR"
"Martinique" : "MTQ"
"Mauritius" : "MUS"
"Malawi" : "MWI"
"Malaysia" : "MYS"
"Namibia" : "NAM"
"New Caledonia" : "NCL"
"Niger" : "NER"
"Norfolk Island" : "NFK"
"Nigeria" : "NGA"
"Nicaragua" : "NIC"
"Niue" : "NIU"
"Netherlands" : "NLD"
"Norway" : "NOR"
"Nepal" : "NPL"
"Nauru" : "NRU"
"New Zealand" : "NZL"
"Oman" : "OMN"
"Pakistan" : "PAK"
"Panama" : "PAN"
"Pitcairn" : "PCN"
"Peru" : "PER"
"Philippines" : "PHL"
"Palau" : "PLW"
"Papua New Guinea" : "PNG"
"Poland" : "POL"
"Puerto Rico" : "PRI"
"North Korea, Democratic People's Republic of" : "PRK"
"Portugal" : "PRT"
"Paraguay" : "PRY"
"French Polynesia" : "PYF"
"Qatar" : "QAT"
"Romania" : "ROU"
"Russian Federation" : "RUS"
"Rwanda" : "RWA"
"Saudi Arabia" : "SAU"
"Sudan" : "SDN"
"Senegal" : "SEN"
"Singapore" : "SGP"
"Solomon Islands" : "SLB"
"Sierra Leone" : "SLE"
"El Salvador" : "SLV"
"San Marino" : "SMR"
"Somalia" : "SOM"
"Serbia" : "SRB"
"Suriname" : "SUR"
"Slovakia" : "SVK"
"Slovenia" : "SVN"
"Sweden" : "SWE"
"Swaziland" : "SWZ"
"Seychelles" : "SYC"
"Syria" : "SYR"
"Chad" : "TCD"
"Togo" : "TGO"
"Thailand" : "THA"
"Tajikistan" : "TJK"
"Tokelau" : "TKL"
"Turkmenistan" : "TKM"
"Timor-Leste" : "TLS"
"Tonga" : "TON"
"Trinidad and Tobago" : "TTO"
"Tunisia" : "TUN"
"Turkey" : "TUR"
"Tuvalu" : "TUV"
"Taiwan, Province of China" : "TWN"
"Tanzania, United Republic of" : "TZA"
"Uganda" : "UGA"
"Ukraine" : "UKR"
"Uruguay" : "URY"
"United States" : "USA"
"United States of Ame" : "USA"
"Uzbekistan" : "UZB"
"Vatican City State, Holy See" : "VAT"
"Saint Vincent and the Grenadines" : "VCT"
"Venezuela, Bolivarian Republic of" : "VEN"
"Virgin Islands, British" : "VGB"
"Virgin Islands, U.S." : "VIR"
"Viet Nam" : "VNM"
"Vanuatu" : "VUT"
"Wallis and Futuna" : "WLF"
"Samoa" : "WSM"
"Yemen" : "YEM"
"South Africa" : "ZAF"
"Zambia" : "ZMB"
"Zimbabwe" : "ZWE"