# Institutional configs
# inst:
#   user_class_file: base name of user class file in classes directory
#   file_type: 'sif' or 'txt' - or custom DEPRECATED todo remove
#   fac_staff: 'manual' = entered into Alma by staff, 'separate' = provided in separate file, 'mixed' = combined in single patron file with students
#   exp_date: boolean - expect a separate file to set the patron expiration date
#   barcodes: boolean = expect a separate file to set the patron barcode
#   user_group_conversion: - a hash/obj that will be used to map values from the original file into alma groups

# Abraham Baldwin Agricultural College
abac:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # want to move to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE:  'STU'

# Armstrong State University
armstrong:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'Student'
    GRADUATE:   'GRAD'

# Albany State University - To be Consolidated with Darton
asu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD: 'UG'
    GRADUATE: 'G'
    FACULTY: 'F' # todo guessed on the sif value

# Atlanta Metropolitan College
atlm:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'

# Augusta University
augusta: # summervile file - patrons in this file (and HSC file, not included) are added to special patron groups
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # want to integrate with peoplesoft
  exp_date:   false
  barcodes:   true
  user_group_conversion: # Hmm? Special Snowflake
#    augdb: # todo figure out a way to handle two distinct files for this institutions patrons
#      UNDERGRAD:  ''
#      GRADUATE:   ''
#    mcgdb:
#      UNDERGRAD:  ''
#      GRADUATE:   ''
    UNDERGRAD: 'Rundergrad'
    GRADUATE: 'Rundergrad'
    FACULTY: 'Rfaculty'
    STAFF: 'Rstaff'
    PARTFAC: 'Rtemp_prt'

# Bainbridge State College
bain:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE:  'STU'

# College of Coastal GA
ccga:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'SEMESTER'
    GRADUATE:  'SEMESTER'

# Clayton State University
clayton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate' # but no file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Columbus State University
csu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate' # No file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'RG'
    GRADUATE:   'RG'

# Dalton State College
dalton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # other signs point to 'separate', but no file provided
  exp_date:   true
  barcodes:   true
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Darton - To be Consolidated with Albany State
darton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'dstu'
    GRADUATE:   'dstu'

# East Georgia State College
ega:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'ST'

# Fort Valley State University
ftv:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'fvstudent'
    GRADUATE:   'fvgrad'

# Georgia Southern University
gasou: # customized ZORVLIB, college and major data included, also patrons from external institutions - see survey results
  user_class_file: 'gasou_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'GR'
    EAST_GA:    'RS'
    FAC_STAFF:  'GF'

# Georgia College
gcsu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   true # separate exp_date file included for fac/staff file
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'GRADUATE'
    FACULTY_FT: 'FACULTY'
    FACULTY_PT: 'FACULTY PT'
    STAFF_FT:   'FACULTY'
    STAFF_PT:   'FACULTY PT'

# Georgia Gwinnett College
ggc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE: 'STU'

# Georgia Highlands College
ghc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    FACSTAFF: 'FACSTAFF'
    UNDERGRAD: 'STUD'

# Gordon State College
gordon:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # ensure facstaff are not included in this file. see survey note
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'

# Georgia Piedmont Technical College
gptc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'UNDERGRAD'

# Georgia State University
# special format
gsu:
  user_class_file: 'gsu_user'
  file_type:  'sif'
  fac_staff:  'mixed'
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo needed to confirm these as they just copy
    L-LAW_FAC: 'L-LAW_FAC'
    PUL2: 'PUL2'
    PUL13: 'PUL13'
    L-STU: 'L-STU'
    PUL11: 'PUL11'
    L-LAW_STAF: 'L-LAW_STAF'
    PUL1: 'PUL1'
    PUL8: 'PUL8'

# Georgia Southwestern State University
gsw:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Kennesaw Sate University - see email from Li for more details
ksu:
  user_class_file: 'ksu_user'
  file_type:  'sif'
  fac_staff:  'mixed' # need more details - special processing occurs, only one file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    undergrad:  'undergrad'
    graduate:   'graduate'

# Middle Georgia State University
mga:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Savannah Sate University
savst:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # survey indicates 'GIL Support' ???
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'GS'

# South Georgia State College
sgsc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # they want to change to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo two campus files...
#    waycross:
#    douglas:
    UNDERGRAD: 'WCSTDT'
    GRADUATE: 'WCSTDT'

# University of Georgia
uga:
  user_class_file: 'uga_user'
  fac_staff: 'mixed'
  exp_date:  false
  barcodes:  false
  user_group_conversion: # todo beta
    '00': 'UNDER PRIV'  # student
    '01': 'FAC'         # faculty
    '02': 'STAFF'       # staff
    '07': 'FAC'         # adj faculty
    '10': 'GRAD PRIV'   # postdoc
    '15': 'STAFF PRIV'  # bor (athens)
    '16': 'STAFF PRIV'  # campus ministers
    '17': 'STAFF PRIV'  # greek house dir
    '18': 'STAFF PRIV'  # mcg sonat employee
    '23': 'STAFF PRIV'  # coop ext serv
    '26': 'STAFF'       # mcg staff
    '27': 'UNDER PRIV'  # mcg student
    '39': 'GRAD PRIV'   # visiting scholar in residence
    '40': 'UNDER PRIV'  # visiting undergrad intern
    '41': 'GRAD PRIV'   # visiting graduate researcher
  user_group_settings:
    'UNDER PRIV':
      weight: 1 # lowest
      exp_date_days: 180
    'FAC':
      weight: 10 # highest
      exp_date_days: 365
    'GRAD PRIV':
      weight: 5
      exp_date_days: 180
    'STAFF':
      weight: 8
      exp_date_days: 365
    'STAFF PRIV':
      weight: 6
      exp_date_days: 180

# University of North Georgia
# todo future usage of facstaff CSV
# todo barcode just is the primary id
ung:
  user_class_file: 'ung_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'student'
    GRADUATE:   'student'

# Valdosta State
vsu:
  user_class_file: 'vsu_user'
  file_type:  'sif'
  fac_staff:  'mixed' # not clear - see survey response
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    STUDNTUND:  'STUDNTUND'
    STUDNTGRA:  'STUDNTGRA'
    CONSORT:    'CONSORT'

# University of West Georgia
# special format
westga: # using a format/process similar to gsu
  user_class_file: 'west_ga_user'
  file_type:  'westga'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo...so many


# testing configs

test_sif:
  user_class_file: 'sif_user'
  file_type:    'sif'
  fac_staff:    'manual'
  exp_date:     true
  barcodes:     true
  expire_users: true
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_gsu:
  file_type: 'gsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_westga:
  file_type: 'gsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_vsu:
  file_type: 'vsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_ga_sou:
  user_class_file: 'ga_sou_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'GR'
    EAST_GA:    'RS'
    FAC_STAFF:  'GF'
test_sif_student_only:
  file_type:  'sif'
  fac_staff:  0
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group: 'A'
    2:
      label: 'GRADUATE'
      alma_group: 'B'
test_uga:
  file_type: 'sif'
  fac_staff: true
  exp_date:  false
  barcodes:   false
  user_group_conversion: # todo beta
    '00': 'UNDER PRIV'  # student
    '01': 'FAC'         # faculty
    '02': 'STAFF'       # staff
    '07': 'FAC'         # adj faculty
    '10': 'GRAD PRIV'   # postdoc
    '15': 'STAFF PRIV'  # bor (athens)
    '16': 'STAFF PRIV'  # campus ministers
    '17': 'STAFF PRIV'  # greek house dir
    '18': 'STAFF PRIV'  # mcg sonat employee
    '23': 'STAFF PRIV'  # coop ext serv
    '26': 'STAFF'       # mcg staff
    '27': 'UNDER PRIV'  # mcg student
    '39': 'GRAD PRIV'   # visiting scholar in residence
    '40': 'UNDER PRIV'  # visiting undergrad intern
    '41': 'GRAD PRIV'   # visiting graduate researcher
  user_group_settings:
    'UNDER PRIV':
      weight: 1 # lowest
      exp_date_days: 180
    'FAC':
      weight: 10 # highest
      exp_date_days: 365
    'GRAD PRIV':
      weight: 5
      exp_date_days: 180
    'STAFF':
      weight: 8
      exp_date_days: 365
    'STAFF PRIV':
      weight: 6
      exp_date_days: 180
test_ksu:
  user_class_file: 'ksu_user'
  file_type:  'sif'
  fac_staff:  'mixed' # need more details - special processing occurs, only one file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    undergrad:    'undergrad'
    graduate:     'graduate'
#    'f-fac/staf': 'facstaff'
test_ung:
  user_class_file: 'ung_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'student'
    GRADUATE:   'student'
