# Institutional configs
# inst:
#   user_class_file: base name of user class file in classes directory
#   file_type: 'sif' or 'txt' - or custom DEPRECATED todo remove
#   fac_staff: 'manual' = entered into Alma by staff, 'separate' = provided in separate file, 'mixed' = combined in single patron file with students
#   exp_date: boolean - expect a separate file to set the patron expiration date
#   barcodes: boolean = expect a separate file to set the patron barcode
#   user_group_conversion: - a hash/obj that will be used to map values from the original file into alma groups

# Abraham Baldwin Agricultural College
abac:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # want to move to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE:  'STU'

# Armstrong State University
armstrong:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'Student'
    GRADUATE:   'GRAD'

# Albany State University - To be Consolidated with Darton
asu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD: 'UG'
    GRADUATE: 'G'
    FACULTY: 'F' # todo guessed on the sif value

# Atlanta Metropolitan College
atlm:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'

# Augusta University
augusta: # summervile file - patrons in this file (and HSC file, not included) are added to special patron groups
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # want to integrate with peoplesoft
  exp_date:   false
  barcodes:   true
  user_group_conversion: # Hmm? Special Snowflake
#    augdb: # todo figure out a way to handle two distinct files for this institutions patrons
#      UNDERGRAD:  ''
#      GRADUATE:   ''
#    mcgdb:
#      UNDERGRAD:  ''
#      GRADUATE:   ''
    UNDERGRAD: 'Rundergrad'
    GRADUATE: 'Rundergrad'
    FACULTY: 'Rfaculty'
    STAFF: 'Rstaff'
    PARTFAC: 'Rtemp_prt'

# Bainbridge State College
bain:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE:  'STU'

# College of Coastal GA
ccga:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'SEMESTER'
    GRADUATE:  'SEMESTER'

# Clayton State University
clayton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate' # but no file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Columbus State University
csu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate' # No file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'RG'
    GRADUATE:   'RG'

# Dalton State College
dalton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # other signs point to 'separate', but no file provided
  exp_date:   true
  barcodes:   true
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Darton - To be Consolidated with Albany State
darton:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'dstu'
    GRADUATE:   'dstu'

# East Georgia State College
ega:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'ST'

# Fort Valley State University
ftv:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'fvstudent'
    GRADUATE:   'fvgrad'

# Georgia Southern University
gasou: # customized ZORVLIB, college and major data included, also patrons from external institutions - see survey results
  user_class_file: 'gasou_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'GR'
    EAST_GA:    'RS'
    FAC_STAFF:  'GF'

# Georgia College
gcsu:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   true # separate exp_date file included for fac/staff file
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'GRADUATE'
    FACULTY_FT: 'FACULTY'
    FACULTY_PT: 'FACULTY PT'
    STAFF_FT:   'FACULTY'
    STAFF_PT:   'FACULTY PT'

# Georgia Gwinnett College
ggc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STU'
    GRADUATE: 'STU'

# Georgia Highlands College
ghc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    FACSTAFF: 'FACSTAFF'
    UNDERGRAD: 'STUD'

# Gordon State College
gordon:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # ensure facstaff are not included in this file. see survey note
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'

# Georgia Piedmont Technical College
gptc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'UNDERGRAD'

# Georgia State University
# special format
gsu:
  user_class_file: 'gsu_user'
  file_type:  'sif'
  fac_staff:  'mixed'
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo needed to confirm these as they just copy
    L-LAW_FAC: 'L-LAW_FAC'
    PUL2: 'PUL2'
    PUL13: 'PUL13'
    L-STU: 'L-STU'
    PUL11: 'PUL11'
    L-LAW_STAF: 'L-LAW_STAF'
    PUL1: 'PUL1'
    PUL8: 'PUL8'

# Georgia Southwestern State University
gsw:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Kennesaw Sate University - see email from Li for more details
ksu:
  user_class_file: 'ksu_user'
  file_type:  'sif'
  fac_staff:  'mixed' # need more details - special processing occurs, only one file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    undergrad:  'undergrad'
    graduate:   'graduate'

# Middle Georgia State University
mga:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'STUDENT'
    GRADUATE:   'STUDENT'

# Savannah Sate University
savst:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # survey indicates 'GIL Support' ???
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'ST'
    GRADUATE:   'GS'

# South Georgia State College
sgsc:
  user_class_file: 'sif_user'
  file_type:  'sif'
  fac_staff:  'manual' # they want to change to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo two campus files...
#    waycross:
#    douglas:
    UNDERGRAD: 'WCSTDT'
    GRADUATE: 'WCSTDT'

# University of Georgia
# todo
uga:
  user_class_file: 'uga_user' # todo rename txt_user...
  fac_staff: 'mixed'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    00:
      label: 'Student'
      alma_group:
    01:
      label: 'Faculty'
      alma_group: ''
    02:
      label: 'Staff'
      alma_group: ''
    03:
      label: 'Alumni'
      alma_group: ''
    04:
      label: 'Retired Faculty/Staff'
      alma_group: ''
    05:
      label: 'Deceased Faculty/Staff'
      alma_group: ''
    06:
      label: 'Prospective Employee'
      alma_group: ''
    07:
      label: 'Adjunct Faculty'
      alma_group: ''
    08:
      label: 'Not Used'
      alma_group: ''
    09:
      label: 'Campus Visitor'
      alma_group: ''
    10:
      label: 'American Language Program (AMLAN)'
      alma_group: ''
    11:
      label: 'Vet Med Student'
      alma_group: ''
    12:
      label: 'Dependent of Student'
      alma_group: ''
    13:
      label: 'Dependent of Faculty/Staff'
      alma_group: ''
    14:
      label: 'Consultant/Contractor'
      alma_group: ''
    15:
      label: 'Board of Regents'
      alma_group: ''
    16:
      label: 'Campus Ministers'
      alma_group: ''
    17:
      label: 'Sorority House Mothers'
      alma_group: ''
    18:
      label: 'MCG SONAT Employees'
      alma_group: ''
    19:
      label: 'ROTC Staff'
      alma_group: ''
    20:
      label: 'SONAT'
      alma_group: ''
    21:
      label: ''
      alma_group: ''
    22:
      label: 'Credit Union Employee'
      alma_group: ''
    23:
      label: 'Cooperative Extension Employee'
      alma_group: ''
    24:
      label: 'Ramsey Access'
      alma_group: ''
    25:
      label: 'Program Participant'
      alma_group: ''
    26:
      label: 'MCG School of Medicine Employee'
      alma_group: ''
    27:
      label: 'MCG School of Medicine Student'
      alma_group: ''
    28:
      label: 'Dependent of Credit Union Staff'
      alma_group: ''
    29:
      label: 'Dependent of Cooperative Extension'
      alma_group: ''
    30:
      label: 'Dependent of Retired Faculty/Staff'
      alma_group: ''
    31:
      label: 'Dependent of Adjunct Faculty'
      alma_group: ''
    32:
      label: 'Dependent of Visiting Faculty'
      alma_group: ''
    33:
      label: 'Dependent of Consultants'
      alma_group: ''
    34:
      label: 'Dependent of Board of Regents'
      alma_group: ''
    35:
      label: 'Dependent of Campus Ministers'
      alma_group: ''
    36:
      label: 'Dependent of Sorority House Mothers'
      alma_group: ''
    37:
      label: 'Dependent of MCG SONAT Staff'
      alma_group: ''
    38:
      label: 'Dependent of ROTC Staff'
      alma_group: ''
    39:
      label: 'Scholar in Residence'
      alma_group: ''
    40:
      label: 'Undergraduate Intern'
      alma_group: ''
    41:
      label: 'Visiting Graduate Student Researcher'
      alma_group: ''
    50:
      label: 'Prospective Student - Applicant'
      alma_group: ''
    55:
      label: 'Prospective Student - Institution Accept'
      alma_group: ''
    60:
      label: 'Prospective Student - Applicant Accept'
      alma_group: ''
    98:
      label: 'Unknown (discard?)'
      alma_group: ''
    99:
      label: 'Historical Student/Record'
      alma_group: ''
  student_class_code_conversion:
    undergraduate: [1, 2, 3, 4]
    graduate: [5]

# University of North Georgia
# todo future usage of facstaff CSV
# todo exp_date input by gil web form - does that generate the exp_date file?
# todo barcode just is the primary id
ung:
  user_class_file: 'ung_user'
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  'student'
    GRADUATE:   'student'

# Valdosta State
vsu:
  user_class_file: 'vsu_user'
  file_type:  'sif'
  fac_staff:  'mixed' # not clear - see survey response
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    STUDNTUND:  'STUDNTUND'
    STUDNTGRA:  'STUDNTGRA'
    CONSORT:    'CONSORT'

# University of West Georgia
# special format
westga: # using a format/process similar to gsu
  user_class_file: 'westga_user'
  file_type:  'westga'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion: # todo...so many


# testing configs

test_sif:
  user_class_file: 'sif_user'
  file_type:    'sif'
  fac_staff:    'manual'
  exp_date:     true
  barcodes:     true
  expire_users: true
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_gsu:
  file_type: 'gsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_westga:
  file_type: 'gsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_vsu:
  file_type: 'vsu'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_sif_student_only:
  file_type:  'sif'
  fac_staff:  0
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group: 'A'
    2:
      label: 'GRADUATE'
      alma_group: 'B'
test_uga:
  file_type: 'sif'
  fac_staff: true
  exp_date:  false
  barcodes:   false
  user_group_conversion:
    00:
      label: 'Student'
      alma_group: 'A'
    01:
      label: 'Faculty'
      alma_group: 'B'
