uga:
  file_type: 'txt'
  fac_staff: 'included'
  user_group_conversion:
    00: 'Student'
    01: 'Faculty'
    02: 'Staff'
    03: 'Alumni'
    04: 'Retired Faculty/Staff'
    05: 'Deceased Faculty/Staff'
    06: 'Prospective Employee'
    07: 'Adjunct Faculty'
    08: 'Not Used'
    09: 'Campus Visitor'
    10: 'American Language Program (AMLAN)'
    11: 'Vet Med Student'
    12: 'Dependent of Student'
    13: 'Dependent of Faculty/Staff'
    14: 'Consultant/Contractor'
    15: 'Board of Regents'
    16: 'Campus Ministers'
    17: 'Sorority House Mothers'
    18: 'MCG SONAT Employees'
    19: 'ROTC Staff'
    20: 'SONAT'
    21: ''
    22: 'Credit Union Employee'
    23: 'Cooperative Extension Employee'
    24: 'Ramsey Access'
    25: 'Program Participant'
    26: 'MCG School of Medicine Employee'
    27: 'MCG School of Medicine Student'
    28: 'Dependent of Credit Union Staff'
    29: 'Dependent of Cooperative Extension'
    30: 'Dependent of Retired Faculty/Staff'
    31: 'Dependent of Adjunct Faculty'
    32: 'Dependent of Visiting Faculty'
    33: 'Dependent of Consultants'
    34: 'Dependent of Board of Regents'
    35: 'Dependent of Campus Ministers'
    36: 'Dependent of Sorority House Mothers'
    37: 'Dependent of MCG SONAT Staff'
    38: 'Dependent of ROTC Staff'
    39: 'Scholar in Residence'
    40: 'Undergraduate Intern'
    41: 'Visiting Graduate Student Researcher'
    50: 'Prospective Student - Applicant'
    55: 'Prospective Student - Institution Accept'
    60: 'Prospective Student - Applicant Accept'
    98: 'Unknown (discard?)'
    99: 'Historical Student/Record'
  student_class_code_conversion:
    undergraduate: [1, 2, 3, 4]
    graduate: [5]
