# Institutional configs
# inst:
#   user_class_file: base name of user class file in classes directory
#   barcodes: boolean = expect a separate file to set the patron barcode
#   user_group_settings: - a hash/obj that will be used to map values from the original file into alma groups

# Abraham Baldwin Agricultural College
abac:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STU'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'STU'
      exp_date_days: 365

# Armstrong State University
armstrong:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'Student'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'GRAD'
       exp_date_days: 365

# Albany State University - To be Consolidated with Darton
asu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'UG'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'G'
      exp_date_days: 365
    FACULTY:
      alma_name: 'F' # todo guessed on the sif value
      exp_date_days: 365

# Atlanta Metropolitan College
atlm:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STU'
      exp_date_days: 180

# Augusta University (Summerville)
augusta:
  path: 'summerville'
  user_class_file: 'sif_user'
  barcodes: true
  user_group_settings:
    UNDERGRAD:
      alma_name: 'Rundergrad'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'Rundergrad'
      exp_date_days: 365
    FACULTY:
      alma_name: 'Rfaculty'
      exp_date_days: 365
    STAFF:
      alma_name: 'Rstaff'
      exp_date_days: 365
    PARTFAC:
      alma_name: 'Rtemp_prt'
      exp_date_days: 365

# Augusta University - MCG
augusta-mcg:
  path: 'mcg'
  user_class_file: 'sif_user'
  barcodes: true
  user_group_settings:
    UNDERGRAD:
      alma_name: 'Mundergrad'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'Mundergrad'
      exp_date_days: 365
    FACULTY:
      alma_name: 'Mfaculty'
      exp_date_days: 365
    STAFF:
      alma_name: 'Mstaff'
      exp_date_days: 365
    PARTFAC:
      alma_name: 'Mtemp_prt'
      exp_date_days: 365

# Bainbridge State College
bain:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STU'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'STU'
      exp_date_days: 365

# College of Coastal GA
ccga:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'SEMESTER'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'SEMESTER'
      exp_date_days: 365

# Clayton State University
clayton:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'STUDENT'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'STUDENT'
       exp_date_days: 365

# Columbus State University
csu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'RG'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'RG'
       exp_date_days: 365

# Dalton State College
dalton:
  user_class_file: 'sif_user'
  barcodes: true
  user_group_settings:
    UNDERGRAD:
       alma_name: 'STUDENT'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'STUDENT'
       exp_date_days: 365

# Darton - To be Consolidated with Albany State
darton:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'dstu'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'dstu'
      exp_date_days: 365

# East Georgia State College
ega:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'ST'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'ST'
       exp_date_days: 365

# Fort Valley State University
ftv:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'fvstudent'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'fvgrad'
       exp_date_days: 365

# Georgia Southern University
gasou:
  user_class_file: 'ga_sou_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'ST'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'GR'
       exp_date_days: 365
    EAST_GA:
       alma_name: 'RS'
       exp_date_days: 180
    FAC_STAFF:
       alma_name: 'GF'
       exp_date_days: 365

# Georgia College
gcsu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STUDENT'
      exp_date_days: 180
    GRADUATE:
       alma_name: 'GRADUATE'
       exp_date_days: 365
    FACULTY_FT:
       alma_name: 'FACULTY'
       exp_date_days: 365
    FACULTY_PT:
       alma_name: 'FACULTY PT'
       exp_date_days: 365
    STAFF_FT:
       alma_name: 'FACULTY'
       exp_date_days: 365
    STAFF_PT:
       alma_name: 'FACULTY PT'
       exp_date_days: 365

# Georgia Gwinnett College
ggc:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STU'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'STU'
      exp_date_days: 180

# Georgia Highlands College
ghc:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    FACSTAFF:
      alma_name: 'FACSTAFF'
      exp_date_days: 365
    UNDERGRAD:
      alma_name: 'STUD'
      exp_date_days: 180

# Gordon State College
gordon:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STUDENT'
      exp_date_days: 180
    STAFF:
      alma_name: 'STAFF'
      exp_date_days: 365
    FACULTY:
      alma_name: 'FACULTY'
      exp_date_days: 365

# Georgia Piedmont Technical College
gptc:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'UNDERGRAD'
      exp_date_days: 180

# Georgia State University
gsu:
  user_class_file: 'gsu_user'
  barcodes: false
  user_group_settings:
    PUL1:
      alma_name: 'PUL1'
      exp_date_days: 180
    L-LAW_FAC:
      alma_name: 'L-LAW_FAC'
      exp_date_days: 365
    PUL2:
      alma_name: 'PUL2'
      exp_date_days: 180
    PUL13:
      alma_name: 'PUL13'
      exp_date_days: 180
    L-STU:
      alma_name: 'L-STU'
      exp_date_days: 180
    PUL11:
      alma_name: 'PUL11'
      exp_date_days: 180
    L-LAW_STAF:
      alma_name: 'L-LAW_STAF'
      exp_date_days: 365
    PUL8:
      alma_name: 'PUL8'
      exp_date_days: 180

# Georgia Southwestern State University
gsw:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
       alma_name: 'STUDENT'
       exp_date_days: 180
    GRADUATE:
       alma_name: 'STUDENT'
       exp_date_days: 180

# Kennesaw Sate University
ksu:
  user_class_file: 'ksu_user'
  barcodes: false
  user_group_settings:
    undergrad:
       alma_name: 'undergrad'
       exp_date_days: 180
    graduate:
       alma_name: 'graduate'
       exp_date_days: 180
    p-fac/staf:
       alma_name: 'facstaff'
       exp_date_days: 180
    f-fac/staf:
       alma_name: 'facstaff'
       exp_date_days: 180

# Middle Georgia State University
mga:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'STUDENT'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'STUDENT'
      exp_date_days: 180

# Savannah Sate University
savst:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'ST'
      exp_date_days: 180
    GRADUATE:
      alma_name: 'GS'
      exp_date_days: 365

# South Georgia State College (Douglas)
sgsc:
  path: 'douglas'
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
     alma_name: 'STDT'
     exp_date_days: 180
    GRADUATE:
     alma_name: 'STDT'
     exp_date_days: 365

# South Georgia State College (Waycross)
sgsc-way:
  path: 'waycross'
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
     alma_name: 'WCSTDT'
     exp_date_days: 180
    GRADUATE:
     alma_name: 'WCSTDT'
     exp_date_days: 365

# University of Georgia
uga:
  user_class_file: 'uga_user'
  barcodes: false
  user_group_conversion:
    '00': 'UNDER PRIV'  # student
    '01': 'FAC'         # faculty
    '02': 'STAFF'       # staff
    '03': 'OUTSIDE'     # alumni
    '04': 'STAFF PRIV'  # retired fac/staff
    '07': 'FAC'         # adj faculty
    '08': 'FAC PRIV'    # emeritus
    '10': 'GRAD PRIV'   # postdoc
    '15': 'STAFF PRIV'  # bor (athens)
    '16': 'STAFF PRIV'  # campus ministers
    '17': 'STAFF PRIV'  # greek house dir
    '23': 'STAFF PRIV'  # coop ext serv
    '26': 'FAC PRIV'    # mcg staff
    '27': 'UNDER PRIV'  # mcg student
  user_group_settings:
    'UNDER PRIV':
      weight: 2 # lowest
      exp_date_days: 180
    'FAC':
      weight: 10 # highest
      exp_date_days: 365
    'FAC PRIV':
      weight: 9
      exp_date_days: 365
    'GRAD PRIV':
      weight: 5
      exp_date_days: 180
    'STAFF':
      weight: 8
      exp_date_days: 365
    'STAFF PRIV':
      weight: 6
      exp_date_days: 180
    'OUTSIDE':
      weight: 1
      exp_date_days:

# University of North Georgia
# todo barcode just is the primary id
ung:
  user_class_file: 'ung_user'
  barcodes: false
  user_group_settings:
    UNDERGRAD:
      alma_name: 'student'
      exp_date_days: 180
    GRADUATE:
       alma_name: 'student'
       exp_date_days: 365

# Valdosta State
vsu:
  user_class_file: 'vsu_user'
  barcodes: false
  user_group_settings:
    STUDNTUND:
       alma_name: 'STUDNTUND'
       exp_date_days: 180
    STUDNTGRA:
       alma_name: 'STUDNTGRA'
       exp_date_days: 365
    STUDNTCOMM:
       alma_name: 'STUDNTCOMM'
       exp_date_days: 365
    CONSORT:
       alma_name: 'CONSORT'
       exp_date_days: 180

# University of West Georgia
westga:
  user_class_file: 'west_ga_user'
  barcodes: false
  user_group_settings:
    undergrad:
      alma_name: 'student'
      exp_date_days: 180

# testing configs

test_sif:
  user_class_file: 'sif_user'
  barcodes: true
  notification_emails:
    - 'mak@uga.edu'
    - 'mkanning@uga.edu'
  user_group_settings:
    UNDERGRAD:
      alma_name: 'ALMA STUDENT'
      exp_date_days: 180

test_sif_campus2:
  path: 'campus2'
  user_class_file: 'sif_user'
  barcodes: true
  user_group_settings:
    UNDERGRAD:
      alma_name: 'ALMA STUDENT'
      exp_date_days: 180
