# Institutional configs
# inst:
#   file_type: 'sif' or 'txt' - tell the scripts what file parsing class to use
#   fac_staff: 'manual' = entered into Alma by staff, 'separate' = provided in separate file, 'mixed' = combined in single patron file with students
#   exp_date: boolean - expect a separate file to set the patron expiration date
#   barcodes: boolean = expect a separate file to set the patron barcode
#   user_group_conversion: - a hash/obj that will be used to map values from the original file into alma groups

# Abraham Baldwin Agricultural College
abac:
  file_type:  'sif'
  fac_staff:  'manual' # want to move to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Armstrong State University
armstrong:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Albany State University - To be Consolidated with Darton
asu:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:

# Atlanta Metropolitan College
atlm:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Augusta University
augusta: # summervile file - patrons in this file (and HSC file, not included) are added to special patron groups
  file_type:  'sif'
  fac_staff:  'manual' # want to integrate with peoplesoft
  exp_date:   false
  barcodes:   true
  user_group_conversion: # Hmm? Special Snowflake
    augdb:
      UNDERGRAD:  ''
      GRADUATE:   ''
    mcgdb:
      UNDERGRAD:  ''
      GRADUATE:   ''

# Bainbridge State College
bain:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# College of Coastal GA
ccga:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Clayton State University
clayton:
  file_type:  'sif'
  fac_staff:  'separate' # but no file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Columbus State University
csu:
  file_type:  'sif'
  fac_staff:  'separate' # No file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Dalton State College
dalton:
  file_type:  'sif'
  fac_staff:  'manual' # other signs point to 'separate', but no file provided
  exp_date:   true
  barcodes:   true
  user_group_conversion:
    UNDERGRAD:  ''

# Darton - To be Consolidated with Albany State
darton:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# East Georgia State College
ega:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Fort Valley State University
ftv:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Georgia Southern University
gasou: # customized ZORVLIB, college and major data included, also patrons from external institutions - see survey results
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''
    EAST_GA:    ''
    FAC_STAFF:  ''

# Georgia College
gcsu:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   true # separate exp_date file included for fac/staff file
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''
    FACULTY_FT: ''
    FACULTY_PT: ''
    STAFF_FT:   ''
    STAFF_PT:   ''

# Georgia Gwinnett College
ggc:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Georgia Highlands College
ghc:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    FACSTAFF: ''
    UNDERGRAD: ''

# Gordon State College
gordon:
  file_type:  'sif'
  fac_staff:  'manual' # ensure facstaff are not included in this file. see survey note
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Georgia Piedmont Technical College
gptc:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''

# Georgia State University
# special format
gsu:
  file_type:  'sif'
  fac_staff:  'mixed'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    L-LAW_FAC: ''
    PUL2: ''
    PUL13: ''
    L-STU: ''
    PUL11: ''
    L-LAW_STAF: ''
    PUL1: ''
    PUL8: ''

# Georgia Southwestern State University
gsw:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   true
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Kennesaw Sate University - see email from Li for more details
ksu:
  file_type:  'sif'
  fac_staff:  'mixed' # need more details - special processing occurs, only one file provided
  exp_date:   false
  barcodes:   false
  user_group_conversion:


# Middle Georgia State University
mga:
  file_type:  'sif'
  fac_staff:  'manual'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Savannah Sate University
savst:
  file_type:  'sif'
  fac_staff:  'manual' # survey indicates 'GIL Support' ???
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# South Georgia State College
sgsc:
  file_type:  'sif'
  fac_staff:  'manual' # they want to change to separate
  exp_date:   false
  barcodes:   false
  user_group_conversion:

# University of Georgia
# todo
uga:
  file_type: 'txt'
  fac_staff: 'mixed'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    00:
      label: 'Student'
      alma_group:
    01:
      label: 'Faculty'
      alma_group: ''
    02:
      label: 'Staff'
      alma_group: ''
    03:
      label: 'Alumni'
      alma_group: ''
    04:
      label: 'Retired Faculty/Staff'
      alma_group: ''
    05:
      label: 'Deceased Faculty/Staff'
      alma_group: ''
    06:
      label: 'Prospective Employee'
      alma_group: ''
    07:
      label: 'Adjunct Faculty'
      alma_group: ''
    08:
      label: 'Not Used'
      alma_group: ''
    09:
      label: 'Campus Visitor'
      alma_group: ''
    10:
      label: 'American Language Program (AMLAN)'
      alma_group: ''
    11:
      label: 'Vet Med Student'
      alma_group: ''
    12:
      label: 'Dependent of Student'
      alma_group: ''
    13:
      label: 'Dependent of Faculty/Staff'
      alma_group: ''
    14:
      label: 'Consultant/Contractor'
      alma_group: ''
    15:
      label: 'Board of Regents'
      alma_group: ''
    16:
      label: 'Campus Ministers'
      alma_group: ''
    17:
      label: 'Sorority House Mothers'
      alma_group: ''
    18:
      label: 'MCG SONAT Employees'
      alma_group: ''
    19:
      label: 'ROTC Staff'
      alma_group: ''
    20:
      label: 'SONAT'
      alma_group: ''
    21:
      label: ''
      alma_group: ''
    22:
      label: 'Credit Union Employee'
      alma_group: ''
    23:
      label: 'Cooperative Extension Employee'
      alma_group: ''
    24:
      label: 'Ramsey Access'
      alma_group: ''
    25:
      label: 'Program Participant'
      alma_group: ''
    26:
      label: 'MCG School of Medicine Employee'
      alma_group: ''
    27:
      label: 'MCG School of Medicine Student'
      alma_group: ''
    28:
      label: 'Dependent of Credit Union Staff'
      alma_group: ''
    29:
      label: 'Dependent of Cooperative Extension'
      alma_group: ''
    30:
      label: 'Dependent of Retired Faculty/Staff'
      alma_group: ''
    31:
      label: 'Dependent of Adjunct Faculty'
      alma_group: ''
    32:
      label: 'Dependent of Visiting Faculty'
      alma_group: ''
    33:
      label: 'Dependent of Consultants'
      alma_group: ''
    34:
      label: 'Dependent of Board of Regents'
      alma_group: ''
    35:
      label: 'Dependent of Campus Ministers'
      alma_group: ''
    36:
      label: 'Dependent of Sorority House Mothers'
      alma_group: ''
    37:
      label: 'Dependent of MCG SONAT Staff'
      alma_group: ''
    38:
      label: 'Dependent of ROTC Staff'
      alma_group: ''
    39:
      label: 'Scholar in Residence'
      alma_group: ''
    40:
      label: 'Undergraduate Intern'
      alma_group: ''
    41:
      label: 'Visiting Graduate Student Researcher'
      alma_group: ''
    50:
      label: 'Prospective Student - Applicant'
      alma_group: ''
    55:
      label: 'Prospective Student - Institution Accept'
      alma_group: ''
    60:
      label: 'Prospective Student - Applicant Accept'
      alma_group: ''
    98:
      label: 'Unknown (discard?)'
      alma_group: ''
    99:
      label: 'Historical Student/Record'
      alma_group: ''
  student_class_code_conversion:
    undergraduate: [1, 2, 3, 4]
    graduate: [5]

# University of North Georgia
# todo CSV facstaff file, ugh
ung:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    UNDERGRAD:  ''
    GRADUATE:   ''

# Valdosta State
vsu:
  file_type:  'sif'
  fac_staff:  'mixed' # not clear - see survey response
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    STUDNTUND:  ''
    STUDNTGRA:  ''
    CONSORT:    ''

# University of West Georgia
# special format
westga: # something really funky going on, see survey results
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   false
  barcodes:   false
  user_group_conversion:


# testing configs

test_sif:
  file_type: 'sif'
  fac_staff: 'manual'
  exp_date:  true
  barcodes:  true
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_gsu_sif:
  file_type: 'sif_plus'
  fac_staff: 'manual'
  exp_date:  false
  barcodes:  false
  user_group_conversion:
    UNDERGRAD:  'ALMA UNDERGRAD'
    GRADUATE:   'ALMA GRAD'
    FAC_STAFF:  'ALMA FACSTAFF'
test_sif_student_only:
  file_type:  'sif'
  fac_staff:  0
  exp_date:   false
  barcodes:   false
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group: 'A'
    2:
      label: 'GRADUATE'
      alma_group: 'B'
test_txt:
  file_type: 'sif'
  fac_staff: true
  exp_date:  false
  barcodes:   false
  user_group_conversion:
    00:
      label: 'Student'
      alma_group: 'A'
    01:
      label: 'Faculty'
      alma_group: 'B'
