# Institutional configs
# inst:
#   user_class_file: base name of user class file in classes directory
#   barcodes: boolean = expect a separate file to set the patron barcode
#   user_group_settings: - a hash/obj that will be used to map values from the original file into alma groups

# Abraham Baldwin Agricultural College
abac:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STU'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STU'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STU'
      weight: 6

# Armstrong State University
armstrong:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'Student'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'Student'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'GRAD'
      weight: 6

# Albany State University - To be Consolidated with Darton
asu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'UG'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'UG'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'G'
      weight: 6
    FACULTY:
      type: 'facstaff'
      alma_name: 'F'
      weight: 9

# Atlanta Metropolitan College
atlm:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STU'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STU'
      weight: 6

# Augusta University (Summerville & MCG)
augusta:
  campus:
    summerville:
      path: 'summerville'
      code: 'SV'
      user_class_file: 'sif_user'
      barcodes: true
      barcode_separator: ","
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'Rundergrad'
          weight: 5
        UNDERGRAD:
          type: 'student'
          alma_name: 'Rundergrad'
          weight: 5
        GRADUATE:
          type: 'student'
          alma_name: 'Rundergrad'
          weight: 6
        FACULTY:
          type: 'facstaff'
          alma_name: 'Rfaculty'
          weight: 9
        STAFF:
          type: 'facstaff'
          alma_name: 'Rstaff'
          weight: 7
        PARTFAC:
          type: 'facstaff'
          alma_name: 'Rtemp_prt'
          weight: 8
    mcg:
      path: 'mcg'
      code: 'HS'
      user_class_file: 'sif_user'
      barcodes: true
      barcode_separator: "\t"
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'Gundergrad'
          weight: 5
        UNDERGRAD:
          type: 'student'
          alma_name: 'Gundergrad'
          weight: 3
        GRADUATE:
          type: 'student'
          alma_name: 'Gundergrad'
          weight: 5
        FACULTY:
          type: 'facstaff'
          alma_name: 'Gfaculty'
          weight: 9
        STAFF:
          type: 'facstaff'
          alma_name: 'Gstaff'
          weight: 7
        PARTFAC:
          type: 'facstaff'
          alma_name: 'Gtemp_prt'
          weight: 6

# Bainbridge State College
bain:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STU'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STU'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STU'
      weight: 6

# College of Coastal GA
ccga:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'SEMESTER'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'SEMESTER'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'SEMESTER'
      weight: 6

# Clayton State University
clayton:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 6
    FAC-STAFF:
      type: 'facstaff'
      alma_name: 'FAC-STAFF'
      weight: 9

# Columbus State University
csu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'RG'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'RG'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'RG'
      weight: 6

# Dalton State College
dalton:
  user_class_file: 'sif_user'
  barcodes: true
  barcode_separator: '|'
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUD'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUD'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STUD'
      weight: 6
    FACULTY:
      type: 'facstaff'
      alma_name: 'FACULTY'
      weight: 9
    STAFF:
      type: 'facstaff'
      alma_name: 'STAFF'
      weight: 8

# Darton - To be Consolidated with Albany State
darton:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'dstu'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'dstu'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'dstu'
      weight: 6

# East Georgia State College
ega:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'ST'
      weight: 6

# Fort Valley State University
ftv:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'fvstudent'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'fvstudent'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'fvgrad'
      weight: 6

# Georgia Southern University
gasou:
  user_class_file: 'ga_sou_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'GR'
      weight: 6
    EAST_GA:
      type: 'student'
      alma_name: 'RS'
      weight: 4
    FAC_STAFF:
      type: 'facstaff'
      alma_name: 'GF'
      weight: 9

# Georgia College
gcsu:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'GRADUATE'
      weight: 6
    'FACULTY FT':
      type: 'facstaff'
      alma_name: 'FACULTY'
      weight: 8
    'FACULTY PT':
      type: 'facstaff'
      alma_name: 'FACULTY PT'
      weight: 9
    'STAFF FT':
      type: 'facstaff'
      alma_name: 'FACULTY'
      weight: 7
    'STAFF PT':
      type: 'facstaff'
      alma_name: 'FACULTY PT'
      weight: 6

# Georgia Gwinnett College
ggc:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUD'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUD'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STUD'
      weight: 6

# Georgia Highlands College
ghc:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUD'
      weight: 5
    FACSTAFF:
      type: 'student'
      alma_name: 'FACSTAFF'
      weight: 8
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUD'
      weight: 5

# Gordon State College
gordon:
  user_class_file: 'gordon_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    STUDENT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    STAFF:
      type: 'facstaff'
      alma_name: 'STAFF'
      weight: 7
    FACULTY:
      type: 'facstaff'
      alma_name: 'FACULTY'
      weight: 9

# Georgia Piedmont Technical College
gptc:
  user_class_file: 'gptc_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5

# Georgia State University
gsu:
  user_class_file: 'gsu_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'PUL1'
      weight: 5
    PUL1:
      type: 'student'
      alma_name: 'PUL1'
      weight: 2
    L-LAW_FAC:
      type: 'facstaff'
      alma_name: 'L-LAW_FAC'
      weight: 7
    PUL2:
      type: 'student'
      alma_name: 'PUL2'
      weight: 3
    PUL13:
      type: 'student'
      alma_name: 'PUL13'
      weight: 4
    L-STU:
      type: 'student'
      alma_name: 'L-STU'
      weight: 5
    PUL11:
      type: 'student'
      alma_name: 'PUL11'
      weight: 5
    L-LAW_STAF:
      type: 'facstaff'
      alma_name: 'L-LAW_STAF'
      weight: 8
    PUL8:
      type: 'student'
      alma_name: 'PUL8'
      weight: 4

# Georgia Southwestern State University
gsw:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 6

# Kennesaw Sate University
ksu:
  user_class_file: 'ksu_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'undergrad'
      weight: 5
    undergrad:
      type: 'student'
      alma_name: 'undergrad'
      weight: 5
    graduate:
      type: 'student'
      alma_name: 'graduate'
      weight: 6
    p-fac/staf:
      type: 'facstaff'
      alma_name: 'p-fac/staf'
      weight: 7
    f-fac/staf:
      type: 'facstaff'
      alma_name: 'f-fac/staf'
      weight: 8

# Middle Georgia State University
mga:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'STUDENT'
      weight: 6

# Savannah Sate University
savst:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ST'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'GS'
      weight: 6

# South Georgia State College (Douglas & Waycross)
sgsc:
  campus:
    waycross:
      path: 'waycross'
      user_class_file: 'sif_user'
      barcodes: false
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'WCSTDT'
          weight: 2
        UNDERGRAD:
          type: 'student'
          alma_name: 'WCSTDT'
          weight: 5
        WCFAC-STF:
          type: 'facstaff'
          alma_name: 'WCFAC-STF'
          weight: 10
    douglas:
      path: 'douglas'
      user_class_file: 'sif_user'
      barcodes: false
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'DCSTDT'
          weight: 1
        UNDERGRAD:
          type: 'student'
          alma_name: 'DCSTDT'
          weight: 4
        DCFAC-STF:
          type: 'facstaff'
          alma_name: 'DCFAC-STF'
          weight: 9

# University of Georgia
uga:
  user_class_file: 'uga_user'
  barcodes: false
  user_group_conversion:
    '00': 'UNDER PRIV'  # student
    '01': 'FAC'         # faculty
    '02': 'STAFF'       # staff
    '03': 'OUTSIDE'     # alumni
    '04': 'STAFF PRIV'  # retired fac/staff
    '07': 'FAC'         # adj faculty
    '08': 'FAC PRIV'    # emeritus
    '10': 'GRAD PRIV'   # postdoc
    '15': 'STAFF PRIV'  # bor (athens)
    '16': 'STAFF PRIV'  # campus ministers
    '17': 'STAFF PRIV'  # greek house dir
    '23': 'STAFF PRIV'  # coop ext serv
    '26': 'FAC PRIV'    # mcg staff
    '27': 'UNDER PRIV'  # mcg student
  user_group_settings:
#    No Default - patrons without groups are to be rejected
    'UNDER PRIV':
      type: 'student'
      alma_name: 'UNDER PRIV'
      weight: 2 # lowest
    'FAC':
      type: 'facstaff'
      alma_name: 'FAC'
      weight: 10 # highest
    'FAC PRIV':
      type: 'facstaff'
      alma_name: 'FAC PRIV'
      weight: 9
    'GRAD PRIV':
      type: 'student'
      alma_name: 'GRAD PRIV'
      weight: 8
    'STAFF':
      type: 'facstaff'
      alma_name: 'STAFF'
      weight: 7
    'STAFF PRIV':
      type: 'facstaff'
      alma_name: 'STAFF PRIV'
      weight: 6
    'OUTSIDE':
      type: 'student'
      alma_name: 'OUTSIDE'
      weight: 1
      
# University of North Georgia
ung:
  user_class_file: 'ung_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'student'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'student'
      weight: 5
    GRADUATE:
      type: 'student'
      alma_name: 'student'
      weight: 6

# Valdosta State
vsu:
  user_class_file: 'vsu_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'STUDNTUND'
      weight: 5
    STUDNTUND:
      type: 'student'
      alma_name: 'STUDNTUND'
      weight: 5
    STUDNTGRA:
      type: 'student'
      alma_name: 'STUDNTGRA'
      weight: 7
    STUDNTCOMM:
      type: 'student'
      alma_name: 'STUDNTCOMM'
      weight: 7
    CONSORT:
      type: 'student'
      alma_name: 'CONSORT'
      weight: 1
    STAFF:
      type: 'facstaff'
      alma_name: 'STAFF'
      weight: 8
    FACCURRENT:
      type: 'facstaff'
      alma_name: 'FACCURRENT'
      weight: 9
    FACCOMMART:
      type: 'facstaff'
      alma_name: 'FACCOMMART'
      weight: 9
       
# University of West Georgia
westga:
  user_class_file: 'sif_user'
  barcodes: false
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'undergrad'
      weight: 2
    UNDERGRAD:
      type: 'student'
      alma_name: 'undergrad'
      weight: 4
    GRADUATE:
      type: 'student'
      alma_name: 'grad'
      weight: 7


# testing configs

test_sif:
  user_class_file: 'sif_user'
  barcodes: true
  barcode_separator: '|'
  notification_emails:
    - 'mak@uga.edu'
    - 'mkanning@uga.edu'
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'ALMA STUDENT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ALMA STUDENT'
      weight: 1
    STAFF:
      type: 'facstaff'
      alma_name: 'ALMA STAFF'
      weight: 10
    'SPACED TEST':
      type: 'facstaff'
      alma_name: 'WORKS'
      weight: 5
      
test_sif_facstaff:
  user_class_file: 'sif_user'
  barcodes: true
  barcode_separator: '|'
  notification_emails:
    - 'mak@uga.edu'
    - 'mkanning@uga.edu'
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'DEFAULT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ALMA STUDENT'
      weight: 1
    STAFF:
      type: 'facstaff'
      alma_name: 'ALMA STAFF'
      weight: 9
    FACULTY:
      type: 'facstaff'
      alma_name: 'ALMA FACULTY'
      weight: 10
    'SPACED TEST':
      type: 'facstaff'
      alma_name: 'WORKS'
      weight: 5
      
test_sif_campus2:
  parent: 'test_sif'
  path: 'campus2'
  user_class_file: 'sif_user'
  barcodes: true
  barcode_separator: ','
  user_group_settings:
    DEFAULT:
      type: 'student'
      alma_name: 'DEFAULT'
      weight: 5
    UNDERGRAD:
      type: 'student'
      alma_name: 'ALMA STUDENT'
      weight: 5

test_sif_empty:
  user_class_file: 'sif_user'

test_exp_override:
  user_class_file: 'sif_user'

# multi campus

test_multi_campus:
  campus:
    campus1:
      path: 'campus1'
      code: 'TST1'
      user_class_file: 'sif_user'
      barcodes: true
      barcode_separator: '|'
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'CAMPUS1 DEFAULT'
          weight: 1
        UNDERGRAD:
          type: 'student'
          alma_name: 'ALMA CAMPUS1 STUDENT'
          weight: 3
        STAFF:
          type: 'facstaff'
          alma_name: 'ALMA CAMPUS1 STAFF'
          weight: 10
    campus2:
      path: 'campus2'
      code: 'TST2'
      user_class_file: 'sif_user'
      barcodes: true
      barcode_separator: ','
      user_group_settings:
        DEFAULT:
          type: 'student'
          alma_name: 'CAMPUS2 DEFAULT'
          weight: 1
        UNDERGRAD:
          type: 'student'
          alma_name: 'ALMA CAMPUS2 STUDENT'
          weight: 2
        STAFF:
          type: 'facstaff'
          alma_name: 'ALMA CAMPUS2 STAFF'
          weight: 9
  notification_emails:
    - 'mak@uga.edu'
    - 'mkanning@uga.edu'