dalton:
  file_type:  'sif'
  fac_staff:  'separate'
  exp_date:   'separate'
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group:
uga:
  file_type: 'txt'
  fac_staff: 'included'
  user_group_conversion:
    00:
      label: 'Student'
      alma_group:
    01:
      label: 'Faculty'
      alma_group: ''
    02:
      label: 'Staff'
      alma_group: ''
    03:
      label: 'Alumni'
      alma_group: ''
    04:
      label: 'Retired Faculty/Staff'
      alma_group: ''
    05:
      label: 'Deceased Faculty/Staff'
      alma_group: ''
    06:
      label: 'Prospective Employee'
      alma_group: ''
    07:
      label: 'Adjunct Faculty'
      alma_group: ''
    08:
      label: 'Not Used'
      alma_group: ''
    09:
      label: 'Campus Visitor'
      alma_group: ''
    10:
      label: 'American Language Program (AMLAN)'
      alma_group: ''
    11:
      label: 'Vet Med Student'
      alma_group: ''
    12:
      label: 'Dependent of Student'
      alma_group: ''
    13:
      label: 'Dependent of Faculty/Staff'
      alma_group: ''
    14:
      label: 'Consultant/Contractor'
      alma_group: ''
    15:
      label: 'Board of Regents'
      alma_group: ''
    16:
      label: 'Campus Ministers'
      alma_group: ''
    17:
      label: 'Sorority House Mothers'
      alma_group: ''
    18:
      label: 'MCG SONAT Employees'
      alma_group: ''
    19:
      label: 'ROTC Staff'
      alma_group: ''
    20:
      label: 'SONAT'
      alma_group: ''
    21:
      label: ''
      alma_group: ''
    22:
      label: 'Credit Union Employee'
      alma_group: ''
    23:
      label: 'Cooperative Extension Employee'
      alma_group: ''
    24:
      label: 'Ramsey Access'
      alma_group: ''
    25:
      label: 'Program Participant'
      alma_group: ''
    26:
      label: 'MCG School of Medicine Employee'
      alma_group: ''
    27:
      label: 'MCG School of Medicine Student'
      alma_group: ''
    28:
      label: 'Dependent of Credit Union Staff'
      alma_group: ''
    29:
      label: 'Dependent of Cooperative Extension'
      alma_group: ''
    30:
      label: 'Dependent of Retired Faculty/Staff'
      alma_group: ''
    31:
      label: 'Dependent of Adjunct Faculty'
      alma_group: ''
    32:
      label: 'Dependent of Visiting Faculty'
      alma_group: ''
    33:
      label: 'Dependent of Consultants'
      alma_group: ''
    34:
      label: 'Dependent of Board of Regents'
      alma_group: ''
    35:
      label: 'Dependent of Campus Ministers'
      alma_group: ''
    36:
      label: 'Dependent of Sorority House Mothers'
      alma_group: ''
    37:
      label: 'Dependent of MCG SONAT Staff'
      alma_group: ''
    38:
      label: 'Dependent of ROTC Staff'
      alma_group: ''
    39:
      label: 'Scholar in Residence'
      alma_group: ''
    40:
      label: 'Undergraduate Intern'
      alma_group: ''
    41:
      label: 'Visiting Graduate Student Researcher'
      alma_group: ''
    50:
      label: 'Prospective Student - Applicant'
      alma_group: ''
    55:
      label: 'Prospective Student - Institution Accept'
      alma_group: ''
    60:
      label: 'Prospective Student - Applicant Accept'
      alma_group: ''
    98:
      label: 'Unknown (discard?)'
      alma_group: ''
    99:
      label: 'Historical Student/Record'
      alma_group: ''
  student_class_code_conversion:
    undergraduate: [1, 2, 3, 4]
    graduate: [5]






test_sif:
  file_type:  'sif' # or 'txt'
  fac_staff_included: 1 # or 0
  barcode_file: 1 # or 0 if included in sif
  exp_date_file: 1  # or 0 if included in sif
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group: 'A'
    2:
      label: 'GRADUATE'
      alma_group: 'B'
test_sif_student_only:
  file_type:  'sif'
  fac_staff_included: 0
  exp_date:   'separate'
  user_group_conversion:
    1:
      label: 'UNDERGRAD'
      alma_group: 'A'
    2:
      label: 'GRADUATE'
      alma_group: 'B'
test_txt:
  file_type:  'sif'
  fac_staff_included: 0
  exp_date:   'separate'
  user_group_conversion:
    00:
      label: 'Student'
      alma_group: 'A'
    01:
      label: 'Faculty'
      alma_group: 'B'
